services:
  mediamtx:
    build: .
    restart: unless-stopped
    container_name: liveu-relay
    environment:
      - AWS_ACCESS_KEY_ID=${SPACES_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SPACES_SECRET_KEY}
      - AWS_DEFAULT_REGION=${SPACES_REGION}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - ./vod:/vod
      - ./scripts:/scripts:ro
      - ./config:/config
    ports:
      - "1935:1935"
      - "8888:8888"
      - "8890:8890/udp"
      - "9997:9997"

  dashboard:
    image: node:20-alpine
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./dashboard:/app
      - ./config:/config
    command: sh -c "npm ci --omit=dev && node server.js"
    ports:
      - "${DASH_PORT:-3000}:${DASH_PORT:-3000}"
