#!/bin/bash

# This shows how to test the API endpoints

echo "Example: Generate a new stream key"
echo ""
echo "Command:"
echo "curl -X POST https://relay-server-record.me3za.me/api/stream-keys \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"Client ABC\"}' \\"
echo "  --user admin:password"
echo ""
echo "Expected response:"
echo "{"
echo "  \"id\": \"abc123def456\","
echo "  \"name\": \"Client ABC\","
echo "  \"key\": \"a1b2c3d4e5f6...64hexchars...a1b2c3d4e5f6\","
echo "  \"active\": true,"
echo "  \"createdAt\": \"2025-10-20T12:00:00Z\","
echo "  \"message\": \"Copy the stream key now...\""
echo "}"
echo ""
echo "---"
echo ""
echo "List all stream keys:"
echo "curl -X GET https://relay-server-record.me3za.me/api/stream-keys \\"
echo "  --user admin:password"
echo ""
echo "---"
echo ""
echo "Delete a stream key:"
echo "curl -X DELETE https://relay-server-record.me3za.me/api/stream-keys/KEY_ID \\"
echo "  --user admin:password"
